version: '2.2'

services:
  supplementapiapp:
    image: supplementapi
    container_name: supplementapiapp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 9090:8080
    networks:
      - supplementbridgenetwork
    restart: always

  

networks:
  supplementbridgenetwork:
    name: exercises-api_mongobridgenetwork 
    external: true

volumes:
  mysupplementmongovolume:
