version: '2.2'

services:
  supplementapiapp:
    image: supplementapi
    container_name: supplementapiapp
    depends_on:
      - supplementsmongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 9090:8080
    networks:
      - supplementbridgenetwork
    restart: always

  supplementsmongodb:
    image: mongo
    container_name: supplementsmongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - supplementbridgenetwork
    volumes:
      - mysupplementmongovolume:/data/db
      - mysupplementmongovolume:/data/configdb
    restart: always

  

networks:
  supplementbridgenetwork:
    driver: bridge

volumes:
  mysupplementmongovolume:
